packages:
  - './packages/*/*'
  - './playground/*'

allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  sharp: false

overrides:
  react: 19.2.3
  react-dom: 19.2.3
  react-native: 0.85.3
  react-native-reanimated: 4.3.1
  react-native-safe-area-context: 5.7.0
  react-native-worklets: 0.8.3

patchedDependencies:
  eslint-plugin-import: packages/devtools/patches/eslint-plugin-import.patch
  eslint-plugin-react: packages/devtools/patches/eslint-plugin-react.patch
  react-native-web: packages/rn/patches/react-native-web.patch
  unicorn-magic: packages/nodejs/patches/unicorn-magic.patch
