packages:
  - './packages/*/*'
  - './playground/*'

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: false

overrides:
  react: 19.2.3
  react-dom: 19.2.3
  react-native: 0.86.0
  react-native-reanimated: 4.5.1
  react-native-safe-area-context: 5.8.0
  react-native-worklets: 0.10.2

patchedDependencies:
  eslint-plugin-import: packages/devtools/patches/eslint-plugin-import.patch
  eslint-plugin-react: packages/devtools/patches/eslint-plugin-react.patch
  react-native-web: packages/core/patches/react-native-web.patch
  unicorn-magic: packages/devtools/patches/unicorn-magic.patch

blockExoticSubdeps: false
