server {
    listen 80;
    server_name localhost;

    gzip on;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/json application/xml+rss;
    gzip_min_length 1024;
    gzip_vary on;

    location /_next/static/ {
        alias /next-static/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        root /next-public;
        try_files $uri @ssr;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location @ssr {
        proxy_pass http://playground_nextjs;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_request_buffering off;
        gzip off;
    }
}
