// need to define route paths in a separated file to avoid circular dependencies
export const rHome = '/'

export const rAccordion = '/accordion'
export const rAlert = '/alert'
export const rBadge = '/badge'
export const rButton = '/button'
export const rButtonGroup = '/button-group'
export const rButtonToggleGroup = '/button-toggle-group'
export const rCheckbox = '/checkbox'
export const rDatePicker = '/date-picker'
export const rDrawer = '/drawer'
export const rForm = '/form'
export const rModal = '/modal'
export const rRadio = '/radio'
export const rSelect = '/select'
export const rSwitch = '/switch'
export const rTextInput = '/text-input'
export const rViewport = '/viewport'
